-- SUPERSEDED. The authoritative schema is supabase/schema.sql on `main`
-- (Person A). This file exists only so this branch merges cleanly; the real
-- generation-layer changes are in supabase/002-generation-layer.sql.
