// GENERATED by scripts/build-corpus-names.mjs — do not edit by hand.
// Real names from data/corpus.boston.json. The home screen shows these as
// evidence the corpus exists, so they must stay in sync with the file.
// Re-run: node scripts/build-corpus-names.mjs

export interface CorpusName {
  name: string;
  type: 'event' | 'person_org' | 'channel';
}

export const CORPUS_NAMES: CorpusName[] = [
  {
    "name": "Venture Café Cambridge — Thursday Gathering",
    "type": "event"
  },
  {
    "name": "MassChallenge Boston Accelerator",
    "type": "event"
  },
  {
    "name": "Boston New Technology (BNT) Product Showcase",
    "type": "event"
  },
  {
    "name": "Startup Boston Week",
    "type": "event"
  },
  {
    "name": "Greentown Labs Events & Tours",
    "type": "event"
  },
  {
    "name": "Harvard Innovation Labs — Public Events",
    "type": "event"
  },
  {
    "name": "MIT Martin Trust Center for Entrepreneurship — Events",
    "type": "event"
  },
  {
    "name": "MIT $100K Entrepreneurship Competition",
    "type": "event"
  },
  {
    "name": "District Hall Boston — Public Innovation Space Events",
    "type": "event"
  },
  {
    "name": "CIC Boston & Cambridge — Community Events",
    "type": "event"
  },
  {
    "name": "Mass Innovation Nights",
    "type": "event"
  },
  {
    "name": "Underscore VC — Community Events & Core Community",
    "type": "event"
  },
  {
    "name": "Babson WIN Lab — Women Innovating Now",
    "type": "event"
  },
  {
    "name": "EforAll (Entrepreneurship for All) — Boston-area Accelerator",
    "type": "event"
  },
  {
    "name": "General Assembly Boston — Free Workshops & Events",
    "type": "event"
  },
  {
    "name": "MassChallenge (org)",
    "type": "person_org"
  },
  {
    "name": "Techstars Boston",
    "type": "person_org"
  },
  {
    "name": "The Engine (MIT-founded tough-tech venture firm)",
    "type": "person_org"
  },
  {
    "name": "IDEA — Northeastern's Student-Run Venture Accelerator",
    "type": "person_org"
  },
  {
    "name": "Innovate@BU / BUild Lab",
    "type": "person_org"
  },
  {
    "name": "Venture Café Cambridge (org)",
    "type": "person_org"
  },
  {
    "name": "MassVentures (state-backed venture funder)",
    "type": "person_org"
  },
  {
    "name": "Massachusetts Technology Collaborative (MassTech)",
    "type": "person_org"
  },
  {
    "name": "Massachusetts Small Business Development Center Network (MSBDC)",
    "type": "person_org"
  },
  {
    "name": "SCORE Boston — Free Mentorship",
    "type": "person_org"
  },
  {
    "name": "Black Economic Council of Massachusetts (BECMA)",
    "type": "person_org"
  },
  {
    "name": "Amplify Latinx",
    "type": "person_org"
  },
  {
    "name": "Pillar VC",
    "type": "person_org"
  },
  {
    "name": "Flybridge Capital Partners",
    "type": "person_org"
  },
  {
    "name": "Glasswing Ventures",
    "type": "person_org"
  },
  {
    "name": "New England Venture Capital Association (NEVCA)",
    "type": "person_org"
  },
  {
    "name": "The Boston Globe — Newsroom Tip Line",
    "type": "person_org"
  },
  {
    "name": "BostInno / Boston Business Journal Inno desk",
    "type": "person_org"
  },
  {
    "name": "WBUR — Boston's NPR Newsroom",
    "type": "person_org"
  },
  {
    "name": "Universal Hub",
    "type": "person_org"
  },
  {
    "name": "Greater Boston Chamber of Commerce",
    "type": "person_org"
  },
  {
    "name": "CIC (Cambridge Innovation Center) — Boston & Cambridge",
    "type": "person_org"
  },
  {
    "name": "Workbar — Greater Boston Coworking",
    "type": "person_org"
  },
  {
    "name": "City of Somerville — Economic Development",
    "type": "person_org"
  },
  {
    "name": "City of Boston — Office of Small Business",
    "type": "person_org"
  },
  {
    "name": "Massachusetts Growth Capital Corporation (MGCC)",
    "type": "person_org"
  },
  {
    "name": "Boston Public Library — Kirstein Business Library & Innovation Center",
    "type": "person_org"
  },
  {
    "name": "Built In Boston",
    "type": "person_org"
  },
  {
    "name": "Boston Business Journal",
    "type": "person_org"
  },
  {
    "name": "r/boston",
    "type": "channel"
  },
  {
    "name": "r/CambridgeMA",
    "type": "channel"
  },
  {
    "name": "r/BostonSocialClub",
    "type": "channel"
  },
  {
    "name": "r/startups (with Boston-specific threads)",
    "type": "channel"
  },
  {
    "name": "Meetup — Boston startup & tech groups",
    "type": "channel"
  },
  {
    "name": "Eventbrite — Boston business & startup events",
    "type": "channel"
  },
  {
    "name": "Venture Café Cambridge — Weekly Programme Newsletter",
    "type": "channel"
  },
  {
    "name": "Startup Boston — Community Newsletter & Slack",
    "type": "channel"
  },
  {
    "name": "Boston.gov — Business Grants & Funding Listings",
    "type": "channel"
  },
  {
    "name": "U.S. Small Business Administration — Massachusetts District Office",
    "type": "channel"
  },
  {
    "name": "Grants.gov — federal grant search (filter to Massachusetts)",
    "type": "channel"
  },
  {
    "name": "SBIR/STTR — America's Seed Fund",
    "type": "channel"
  },
  {
    "name": "Product Hunt (launch channel)",
    "type": "channel"
  },
  {
    "name": "Indie Hackers",
    "type": "channel"
  },
  {
    "name": "LinkedIn — Boston founder & local-business content",
    "type": "channel"
  },
  {
    "name": "Nextdoor — Boston neighbourhoods",
    "type": "channel"
  }
];
